### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by bakrun** [MattiDragon/PowerNetworks#1]
### Description of the issue

I was generating with a solar panel and supplying power to an powered furnace through a coil, but suddenly an error occurred.

And when I run the world again, it crashes with an error.

### Reproduction steps

1. Install the solar panel and connect any coil underneath
2. Connect the powered furnace and the coil and connect the two coils with a wire.
3. After putting a stone in the furnace and setting the time to night, the game crashes when the furnace works.

### Mod version

1.0.1

### Operating System

Windows 10

### Minecraft version

1.19.4

### Other mods

fabric-api-0.76.0+1.19.4
energizedpower-1.19.4-1.5.0-fabric [curseforge link](https://legacy.curseforge.com/minecraft/mc-mods/energized-power)

### Server

Not tested

### Client

Happens

### Logs

https://pastebin.com/6ESdUe8g

### Crash Report

https://pastebin.com/6YpTRsA9

**Comment by MattiDragon** [comment]
Managed to reproduce. Now I need to figure out how to fix this. My energy distribution algorithm is broken
